name: interiorshare
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  image_picker: ^0.8.8
  firebase_core: ^2.13.1
  arkit_plugin: ^1.0.6
  path_provider: ^2.0.15
  flutter_joystick: ^0.0.3
  #flutter_joystick: ^0.1.2
  #ar_flutter_plugin: ^0.7.3
  #joystick: ^1.1.0
  #control_pad_plus: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #firebase_core: ^2.13.1
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
